### ISSUE TITLE
.bin symlinks

### ISSUE THREAD

**Issue by ChrisMcKenzie** [wercker/step-npm-install#10]
in cases where i have `node_modules` installed on my host machine and then run `wercker build` npm will install but the symlinks will remain the same as the host therefore any thing that tries to run something from node_modules/.bin will fail

**Comment by hatchan** [comment]
Interresting, not sure if we can do something about this. A workaround is to clear the `node_modules` folder before running `npm install` on either your host or during a wercker build.

**Comment by ChrisMcKenzie** [comment]
that is what I am currently forced to do thanks a lot.
