### ISSUE TITLE
npm-install failing - Error: Cannot find module 'npm-registry-client'

### ISSUE THREAD

**Issue by pettersoderlund** [wercker/step-npm-install#13]
Im getting this error since yesterday. I have not changed anything to the settings that I know of that would affect this... 

Any ideas?

From the build log: 

cd $WERCKER_SOURCE_DIR
$ export WERCKER_STEP_ROOT="/wercker/steps/wercker/npm-install/1.1.4"
$ export WERCKER_STEP_ID="81bf9d31-e5f6-4535-8da1-766b832ef915"
$ export WERCKER_STEP_NAME="npm-install"
$ export WERCKER_REPORT_NUMBERS_FILE="$WERCKER_REPORT_DIR/$WERCKER_STEP_ID/numbers.ini"
$ export WERCKER_REPORT_MESSAGE_FILE="$WERCKER_REPORT_DIR/$WERCKER_STEP_ID/message.txt"
$ export WERCKER_REPORT_ARTIFACTS_DIR="$WERCKER_REPORT_DIR/$WERCKER_STEP_ID/artifacts"
$ mkdir -p $WERCKER_REPORT_ARTIFACTS_DIR
$ export WERCKER_STEP_TEMP="/tmp/$WERCKER_STEP_ID"
$ source '/wercker/wercker-build-essentials/init.sh'
$ mkdir -p $WERCKER_STEP_TEMP
$ export WERCKER_NPM_INSTALL_USE_CACHE="true"
$ export WERCKER_NPM_INSTALL_CLEAR_CACHE_ON_FAILED="true"
$ source "$WERCKER_STEP_ROOT/run.sh"
Using wercker cache
Creating $WERCKER_CACHE_DIR/wercker/npm
Configuring npm to use wercker cache

module.js:340
    throw err;
          ^
Error: Cannot find module 'npm-registry-client'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/npm/lib/cache/caching-client.js:9:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by Tonnu** [comment]
Hi there,

Could you try clearing the cache under application settings and then doing a rebuild?

**Comment by pettersoderlund** [comment]
Hi @Tonnu , 
Thanks for your quick answer! 
I tried clearing the cache but still the build fails with the same error.

**Comment by Tonnu** [comment]
Hia, could you maybe enable wercker support and shoot in a ticket using the green question mark? That way I'll be able to check out your builds to get an idea of what's going on.

Thanks!

**Comment by pettersoderlund** [comment]
I'll do that straight away, thanks!

**Comment by hatchan** [comment]
@pettersoderlund This seems to be an issue with npm itself: https://github.com/npm/npm/issues/10492

I'm not sure when the the fix will be released, so if possible, try to install a older version which doesn't have the bug.
